FROM openjdk:8
RUN apt-get update
RUN apt-get -y install maven
WORKDIR /root
CMD cd /root/chronstore/Chord;mvn install -Dmaven.test.skip=true;cd /root/chronstore/Fusion;mvn install -Dmaven.test.skip=true;cd /root/chronstore/ObjectStore;mvn compile exec:java
ENV LD_LIBRARY_PATH /usr/local/lib:/usr/local/share/java:/Users/shaileshkelkar/Desktop/Distributed\ Systems/Project/chronstore/Fusion/src/main/java/edu/utaustin/fusion
ENV JAVA_LIBRARY_PATH /usr/local/lib:/usr/local/share/java:/Users/shaileshkelkar/Desktop/Distributed\ Systems/Project/chronstore/Fusion/src/main/java/edu/utaustin/fusion
